//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 11:40:49 AM CET 
//


package com.ancit.genxtools.dbc.model;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://kayak.2codeornot2code.org/1.0}BasicSignalType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}MuxGroup" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Notes" minOccurs="0"/&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Consumer" minOccurs="0"/&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Value" minOccurs="0"/&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}LabelSet" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class Multiplex
    extends BasicSignalType
{

    protected List<MuxGroup> muxGroup;
    protected String notes;
    protected Consumer consumer;
    protected Value value;
    protected LabelSet labelSet;

    /**
     * Gets the value of the muxGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the muxGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMuxGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MuxGroup }
     * 
     * 
     */
    public List<MuxGroup> getMuxGroup() {
        if (muxGroup == null) {
            muxGroup = new ArrayList<MuxGroup>();
        }
        return this.muxGroup;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the consumer property.
     * 
     * @return
     *     possible object is
     *     {@link Consumer }
     *     
     */
    public Consumer getConsumer() {
        return consumer;
    }

    /**
     * Sets the value of the consumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Consumer }
     *     
     */
    public void setConsumer(Consumer value) {
        this.consumer = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setValue(Value value) {
        this.value = value;
    }

    /**
     * Gets the value of the labelSet property.
     * 
     * @return
     *     possible object is
     *     {@link LabelSet }
     *     
     */
    public LabelSet getLabelSet() {
        return labelSet;
    }

    /**
     * Sets the value of the labelSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelSet }
     *     
     */
    public void setLabelSet(LabelSet value) {
        this.labelSet = value;
    }

}
