//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.06 at 11:40:49 AM CET 
//

package com.ancit.genxtools.dbc.model;

import java.util.ArrayList;
import java.util.List;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Document"/&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Node" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://kayak.2codeornot2code.org/1.0}Bus" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */

public class NetworkDefinition {

	protected Document document;
	protected List<Nodes> node;
	protected List<Bus> bus;
	protected List<EnvironmentVariables> envVariables;

	public List<EnvironmentVariables> getEnvVariables() {
		if (envVariables == null) {
			envVariables = new ArrayList<EnvironmentVariables>();
		}
		return this.envVariables;
	}

	/**
	 * Gets the value of the document property.
	 * 
	 * @return possible object is {@link Document }
	 * 
	 */
	public Document getDocument() {
		return document;
	}

	/**
	 * Sets the value of the document property.
	 * 
	 * @param value
	 *            allowed object is {@link Document }
	 * 
	 */
	public void setDocument(Document value) {
		this.document = value;
	}

	/**
	 * Gets the value of the node property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the node property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getNode().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Node }
	 * 
	 * 
	 */
	public List<Nodes> getNode() {
		if (node == null) {
			node = new ArrayList<Nodes>();
		}
		return this.node;
	}

	/**
	 * Gets the value of the bus property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the bus property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBus().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Bus }
	 * 
	 * 
	 */
	public List<Bus> getBus() {
		if (bus == null) {
			bus = new ArrayList<Bus>();
		}
		return this.bus;
	}

}
